[package]
<<<<<<< HEAD:rust_time/tomfuckery/Cargo.toml
name = "tomfuckery"
=======
name = "docstest"
>>>>>>> 73fc925092698568bfa77d717d81748a9ce98546:rust_time/docstest/Cargo.toml
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
